version: 2.1
jobs:
  build:
    docker:
      - image: fr3akyphantom/droid-builder:latest
    environment:
      MANIFEST_BRANCH: 'twrp-6.0'
      # PBRP_BRANCH: 'android-9.0'
      VERSION: '2.9.0'
      VENDOR: 'WALTON'
      CODENAME: 'Primo_RX5'
      BUILD_LUNCH: 'omni_Primo_RX5-userdebug'
      TEST_BUILD: 'true'
    working_directory: /home/builder/pitchblack
    steps:
      # - checkout
      - run:
          name: AIO Build
          command: |
            echo "Set GitAuth Infos"
            git config --global user.email $GitHubMail
            git config --global user.name $GitHubName
            git config --global color.ui true
            /bin/bash \<< EOF
            asciinema rec CI.cast -q -y
            wget -q https://gist.github.com/rokibhasansagar/62f90b84f5de4fcb3b1313096710b1aa/raw/build.sh
            chmod a+x build.sh
            source build.sh
            exit
            EOF
            asciinema cat CI.cast > CI.cast.log
      - store_artifacts:
          path: CI.log
          destination: PBRP_${CODENAME}_${CIRCLE_BUILD_NUM}_CI.log
      - store_artifacts:
          path: CI.cast.log
          destination: PBRP_${CODENAME}_${CIRCLE_BUILD_NUM}_CI.cast.log
      - run:
          name: Upload CI Log
          command: |
            curl --upload-file CI.log https://transfer.sh/PBRP_${CODENAME}_${CIRCLE_BUILD_NUM}_CI.log && echo -e "\n\n"
            curl --upload-file CI.cast.log https://transfer.sh/PBRP_${CODENAME}_${CIRCLE_BUILD_NUM}_CI.cast.log && echo -e "\n\n\n"
          when: always

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: personal-envs
