version: 2.1
jobs:
  build:
    docker:
      - image: fr3akyphantom/droid-builder:focal
    environment:
      MANIFEST_BRANCH: 'android-6.0'
      # PBRP_BRANCH: 'android-9.0'
      VERSION: '2.9.1'
      VENDOR: 'WALTON'
      CODENAME: 'Primo_RX5'
      FLAVOR: 'userdebug'
      TEST_BUILD: 'true'
      PB_ENGLISH: 'true'
      MAINTAINER: '@fr3akyphantom'
      CHANGELOG: |
        What's done?
        - Update done for xx
        What's fixed?
        - Fixed yy things
        - Changed anything else
        And something else
      TGChat: "-350195336"
    working_directory: /home/builder/pitchblack
    steps:
      - run:
          name: AIO Build
          command: |
            wget -q https://gist.github.com/rokibhasansagar/10f470348d956698ef64d155522f789e/raw/build.sh
            chmod a+x build.sh
            source build.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: personal-envs
